const {
  'REACT_APP_MARVEL_PUBLIC_KEY': MARVEL_PUBLIC_KEY,
  'REACT_APP_MARVEL_PRIVATE_KEY': MARVEL_PRIVATE_KEY
} = process.env;
const API_MARVEL_PUBLIC = 'https://gateway.marvel.com:443/v1/public';

export {API_MARVEL_PUBLIC, MARVEL_PUBLIC_KEY, MARVEL_PRIVATE_KEY};
