language: node_js
node_js:
  - "12"
before_install:
  - npm install -g yarn now
  - cd client
script: yarn run test-ci
after_success: yarn run coveralls
deploy:
  provider: script
  script: now --target production --token=$NOW_TOKEN
  skip_cleanup: true
  on:
    branch: master
