version: '3'
services:
  web:
    container_name: marvel
    build: .
    image: marvel
    ports:
      - "80:8000"
    restart: always
    env_file: ./server/.env
    environment:
      NODE_ENV: production
      PORT: 8000
