version: '3'
services:
  server:
    container_name: marvel-server
    build:
      context: ./server
    image: marvel/server
    volumes: # mounting following volumes allows the livereload
      - ./server:/var/marvel
      - /var/marvel/node_modules
    ports:
      - "8000:8000"
    env_file: ./server/.env
  client:
    container_name: marvel-client
    build:
      context: ./client
    image: marvel/client
    volumes: # mounting following volumes allows the livereload
      - ./client:/var/marvel
      - /var/marvel/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_MARVEL_PROXY_API=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
